apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-app:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_POSTGRES_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: SPRING_POSTGRES_USERNAME
              value: "myapplication"
            - name: SPRING_POSTGRES_PASSWORD
              value: "M3P@ssw0rd!"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
